integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: main
  pip_install: .[gpu-flash2]
- integration_type: git_repo
  git_repo: JackZ-db/composer
  git_branch: dev
  pip_install: .[all]

scheduling:
  priority: medium

command: |
  cd llm-foundry/scripts
  composer train/train.py /mnt/config/parameters.yaml
  python inference/convert_composer_to_hf.py \
    --composer_path ./mpt-125m-chinchilla-regression/checkpoints/latest-rank0.pt \
    --hf_output_path ./hf-checkpoints/
image: mosaicml/pytorch:2.3.1_cu121-python3.11-ubuntu20.04
name: mpt-7b-chinchilla-regression

cluster: r15z4p1
#cluster: r1z1
compute:
  gpus: 8

parameters:
  run_name: mpt-125m-chinchilla-regression
  
  variables:
    data_local: ./my-copy-c4
    data_remote: oci://mosaicml-internal-regression-test/c4-copy/
    max_seq_len: 2048
    global_seed: 17

  max_seq_len: ${variables.max_seq_len}

  model:
    name: mpt_causal_lm
    init_device: meta
    d_model: 4096
    n_heads: 32
    n_layers: 32
    expansion_ratio: 4
    max_seq_len: ${variables.max_seq_len}
    vocab_size: 50368
    attn_config:
      attn_impl: flash

  tokenizer:
    name: EleutherAI/gpt-neox-20b
    kwargs:
      model_max_length: ${variables.max_seq_len}

  train_loader:
    name: text
    dataset:
      local: ${variables.data_local}
      remote: ${variables.data_remote}
      split: train_small
      shuffle: true
      max_seq_len: ${variables.max_seq_len}
      shuffle_seed: ${variables.global_seed}
    drop_last: true
    num_workers: 8

  eval_loader:
    name: text
    dataset:
      local: ${variables.data_local}
      remote: ${variables.data_remote}
      split: val_small
      shuffle: false
      max_seq_len: ${variables.max_seq_len}
      shuffle_seed: ${variables.global_seed}
    drop_last: false
    num_workers: 8

  scheduler:
    name: cosine_with_warmup
    t_warmup: 100ba
    alpha_f: 0.1

  optimizer:
    name: decoupled_adamw
    lr: 6.0e-4
    betas:
    - 0.9
    - 0.95
    eps: 1.0e-08
    weight_decay: 0.0

  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  max_duration: 100ba
  eval_interval: 50ba
  eval_first: false
  eval_subset_num_batches: -1
  global_train_batch_size: 256

  seed: ${variables.global_seed}
  device_eval_batch_size: 16
  device_train_microbatch_size: 2
  precision: amp_bf16

  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE
    activation_checkpointing: false
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    verbose: false

  progress_bar: false
  log_to_console: true
  console_log_interval: 1ba

  callbacks:
    speed_monitor:
      window_size: 10
    lr_monitor: {}
    memory_monitor: {}
    runtime_estimator: {}
    memory_snapshot: {}

  save_interval: 500ba
  save_folder: ./{run_name}/checkpoints

  loggers:
    mlflow: 
      experiment_name: /Shared/Runtime/automicrobatch
      run_name: 7b-32-2-full
    #   group:   # Name of WandB group